### PR TITLE
bump jose4j version to 0.9.5

### PR DESCRIPTION
**Pull request by ZheSun88**
resolve https://github.com/advisories/GHSA-6qvw-249j-h44c

### CODE REVIEW

**Comment by ZheSun88** [comment]
hi @andreblanke we are using this dependency in our project. and recently we got reports that the version of jose4j is vulnerable. 
can you take a look ? thanks

**Comment by andreblanke** [comment]
Thank you for your contribution and make me aware of the CVE. I don't think the vulnerability really affects webpush-java since nothing is deserialized by the library, but I'll update JOSE4j and publish a new version

**Comment by ZheSun88** [comment]
Thanks. Can you let me know when the new version got released?

**Comment by andreblanke** [comment]
Whoops, sorry for that. I thought version 6.1.2 was already available on Maven Central, but turns out there was an error during publish that I missed. The new version should be available from now on

**Comment by ZheSun88** [comment]
thanks. now it is available.

**Pull request merged**
